- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday
        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Dokploy
              url: https://deploy.wuhao.dev
            - title: Reference
              url: https://ref.wuhao.dev
            - title: Toolhub
              url: https://tool.wuhao.dev
            - title: Umami
              url: https://umami.wuhao.dev/dashboard
            - title: VPN
              url: https://v.wuhao.dev
        - type: server-stats
          servers:
            - type: local
              name: Services

    - size: full
      widgets:
        - type: rss
          limit: 10
          collapse-after: 5
          cache: 12h
          style: detailed-list
          feeds:
            - url: https://antfu.me/feed.xml
            - url: https://feeds.feedburner.com/ruanyifeng
            - url: https://colobu.com/atom.xml
            - url: https://www.piglei.com/feeds/latest/
            - url: https://innei.in/feed
            - url: https://springwood.me/feed/

    - size: small
      widgets:
        - type: weather
          location: Shanghai, China
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true
        - type: videos
          style: vertical-list
          channels:
            - UCilwQlk62k1z7aUEZPOB6yw # xiaolinshuo
            - UCjuNibFJ21MiSNpu8LZyV4w # chaijing
            - UCapPWG_ppEuYvelriReTcOA # erye
            - UCYPT3wl0MgbOz63ho166KOw # xiaodao
